package com.brielage.uitleendienst.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable (tableName = "beschikbaarItem")
public class BeschikbaarItem {
    private String          id;
    private UitleenbaarItem uitleenbaarItem;
    private Magazijn        magazijn;
    private int             aantalTotaal;
    private int             aantalBeschikbaar;
    private int             aantalGereserveerd;

    public BeschikbaarItem () {}

    public BeschikbaarItem (
            UitleenbaarItem uitleenbaarItem,
            Magazijn magazijn,
            Integer aantalTotaal,
            Integer aantalBeschikbaar,
            Integer aantalGereserveerd) {
        this.uitleenbaarItem    = uitleenbaarItem;
        this.magazijn           = magazijn;
        this.aantalTotaal       = aantalTotaal;
        this.aantalBeschikbaar  = aantalBeschikbaar;
        this.aantalGereserveerd = aantalGereserveerd;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId () {
        return id;
    }

    @DynamoDBAttribute
    public void setId (String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public UitleenbaarItem getUitleenbaarItem () {
        return uitleenbaarItem;
    }

    @DynamoDBAttribute
    public void setUitleenbaarItem (UitleenbaarItem uitleenbaarItem) {
        this.uitleenbaarItem = uitleenbaarItem;
    }

    @DynamoDBAttribute
    public Magazijn getMagazijn () {
        return magazijn;
    }

    @DynamoDBAttribute
    public void setMagazijn (Magazijn magazijn) {
        this.magazijn = magazijn;
    }

    @DynamoDBAttribute
    public Integer getAantalTotaal () {
        return aantalTotaal;
    }

    @DynamoDBAttribute
    public void setAantalTotaal (Integer aantalTotaal) {
        this.aantalTotaal = aantalTotaal;
    }

    @DynamoDBAttribute
    public Integer getAantalBeschikbaar () {
        return aantalBeschikbaar;
    }

    @DynamoDBAttribute
    public void setAantalBeschikbaar (Integer aantalBeschikbaar) {
        this.aantalBeschikbaar = aantalBeschikbaar;
    }

    @DynamoDBAttribute
    public Integer getAantalGereserveerd () {
        return aantalGereserveerd;
    }

    @DynamoDBAttribute
    public void setAantalGereserveerd (Integer aantalGereserveerd) {
        this.aantalGereserveerd = aantalGereserveerd;
    }

    @Override
    public String toString () {
        return "BeschikbaarItem{" +
                "id='" + id + '\'' +
                ", uitleenbaarItem=" + uitleenbaarItem +
                ", magazijn=" + magazijn +
                ", aantalTotaal=" + aantalTotaal +
                ", aantalBeschikbaar=" + aantalBeschikbaar +
                ", aantalGereserveerd=" + aantalGereserveerd +
                '}';
    }
}
