package com.brielage.uitleendienst.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable (tableName = "contactMagazijn")
public class ContactMagazijn {
    private String   id;
    private Persoon  persoon;
    private Magazijn magazijn;
    private String   opmerking;

    public ContactMagazijn () {}

    public ContactMagazijn (
            Persoon persoon,
            Magazijn magazijn,
            String opmerking) {
        this.persoon   = persoon;
        this.magazijn  = magazijn;
        this.opmerking = opmerking;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId () {
        return id;
    }

    @DynamoDBAttribute
    public void setId (String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public Persoon getPersoon () {
        return persoon;
    }

    @DynamoDBAttribute
    public void setPersoon (Persoon persoon) {
        this.persoon = persoon;
    }

    @DynamoDBAttribute
    public Magazijn getMagazijn () {
        return magazijn;
    }

    @DynamoDBAttribute
    public void setMagazijn (Magazijn magazijn) {
        this.magazijn = magazijn;
    }

    @DynamoDBAttribute
    public String getOpmerking () {
        return opmerking;
    }

    @DynamoDBAttribute
    public void setOpmerking (String opmerking) {
        this.opmerking = opmerking;
    }

    @Override
    public String toString () {
        return "ContactMagazijn{" +
                "id='" + id + '\'' +
                ", persoon=" + persoon +
                ", magazijn=" + magazijn +
                ", opmerking='" + opmerking + '\'' +
                '}';
    }
}
