package com.brielage.uitleendienst.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable (tableName = "organisatie")
public class Organisatie {
    private String id;
    private String naam;
    private String adres;
    private String telefoon;
    private String email;
    private String opmerking;

    public Organisatie () {}

    public Organisatie (
            String naam,
            String adres,
            String telefoon,
            String email,
            String opmerking) {
        this.naam      = naam;
        this.adres     = adres;
        this.telefoon  = telefoon;
        this.email     = email;
        this.opmerking = opmerking;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId () {
        return id;
    }

    @DynamoDBAttribute
    public String getNaam () {return naam;}

    @DynamoDBAttribute
    public void setNaam (final String naam) {this.naam = naam;}

    @DynamoDBAttribute
    public void setId (String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getAdres () {
        return adres;
    }

    @DynamoDBAttribute
    public void setAdres (String adres) {
        this.adres = adres;
    }

    @DynamoDBAttribute
    public String getTelefoon () {
        return telefoon;
    }

    @DynamoDBAttribute
    public void setTelefoon (String telefoon) {
        this.telefoon = telefoon;
    }

    @DynamoDBAttribute
    public String getEmail () {
        return email;
    }

    @DynamoDBAttribute
    public void setEmail (String email) {
        this.email = email;
    }

    @DynamoDBAttribute
    public String getOpmerking () {
        return opmerking;
    }

    @DynamoDBAttribute
    public void setOpmerking (String opmerking) {
        this.opmerking = opmerking;
    }

    @Override
    public String toString () {
        return "Organisatie{" +
                "id='" + id + '\'' +
                ", naam='" + naam + '\'' +
                ", adres='" + adres + '\'' +
                ", telefoon='" + telefoon + '\'' +
                ", email='" + email + '\'' +
                ", opmerking='" + opmerking + '\'' +
                '}';
    }
}
