package com.brielage.uitleendienst.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable (tableName = "rol")
public class Rol {
    private String id;
    private String naam;
    private String omschrijving;

    public Rol () {}

    public Rol (
            String naam,
            String omschrijving) {
        this.naam         = naam;
        this.omschrijving = omschrijving;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId () {
        return id;
    }

    @DynamoDBAttribute
    public void setId (String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getNaam () {
        return naam;
    }

    @DynamoDBAttribute
    public void setNaam (String naam) {
        this.naam = naam;
    }

    @DynamoDBAttribute
    public String getOmschrijving () {
        return omschrijving;
    }

    @DynamoDBAttribute
    public void setOmschrijving (String omschrijving) {
        this.omschrijving = omschrijving;
    }

    @Override
    public String toString () {
        return "Rol{" +
                "id='" + id + '\'' +
                ", naam='" + naam + '\'' +
                ", omschrijving='" + omschrijving + '\'' +
                '}';
    }
}
