package com.brielage.uitleendienst.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;

@DynamoDBTable (tableName = "uitleenbaarItem")
public class UitleenbaarItem {
    private String    id;
    private String    naam;
    private int   eenheid;
    private float     prijs;
    private Date      periode;
    private Categorie categorie;

    public UitleenbaarItem () {}

    public UitleenbaarItem (
            String naam,
            int eenheid,
            float prijs,
            Date periode,
            Categorie categorie) {
        this.naam      = naam;
        this.eenheid   = eenheid;
        this.prijs     = prijs;
        this.periode   = periode;
        this.categorie = categorie;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId () {
        return id;
    }

    @DynamoDBAttribute
    public void setId (String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getNaam () {
        return naam;
    }

    @DynamoDBAttribute
    public void setNaam (String naam) {
        this.naam = naam;
    }

    @DynamoDBAttribute
    public int getEenheid () {
        return eenheid;
    }

    @DynamoDBAttribute
    public void setEenheid (int eenheid) {
        this.eenheid = eenheid;
    }

    @DynamoDBAttribute
    public float getPrijs () {
        return prijs;
    }

    @DynamoDBAttribute
    public void setPrijs (float prijs) {
        this.prijs = prijs;
    }

    @DynamoDBAttribute
    public Date getPeriode () {
        return periode;
    }

    @DynamoDBAttribute
    public void setPeriode (Date periode) {
        this.periode = periode;
    }

    @DynamoDBAttribute
    public Categorie getCategorie () {
        return categorie;
    }

    @DynamoDBAttribute
    public void setCategorie (Categorie categorie) {
        this.categorie = categorie;
    }

    @Override
    public String toString () {
        return "UitleenbaarItem{" +
                "id='" + id + '\'' +
                ", naam='" + naam + '\'' +
                ", eenheid=" + eenheid +
                ", prijs=" + prijs +
                ", periode=" + periode +
                ", categorie=" + categorie +
                '}';
    }
}
